export const elements = [
    {
      id: 1,
      name: 'Bitcoin',
      symbol: 'BTC',
      price: 57200,
      change: 0.25,
      icon: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png',
      cap: '60000',
    },
    {

      id: 2,
      name: 'Ethereum',
      symbol: 'ETH',
      price: 3570,
      change: -0.25,
      icon: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
      cap: '4000',
    },
    {
      id: 3,
      name: 'Bitcoin',
      symbol: 'BTC',
      price: 57200,
      change: -0.25,
      icon: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png',
      cap: '6000',
    },
    {
      id: 4,
      name: 'Ethereum',
      symbol: 'ETH',
      price: 3570,
      change: 0.25,
      icon: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
      cap: '4000',
    },
    {
      id: 5,
      name: 'Bitcoin',
      symbol: 'BTC',
      price: 57200,
      change: -0.25,
      icon: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png',
      cap: '62000',
    },
    {
      id: 6,
      name: 'Ethereum',
      symbol: 'ETH',
      price: 3570,
      change: 0.25,
      icon: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
      cap: '5000',
    },
  ];